import { ListingFieldSchema } from "@/types/listings";

export const apartmentSchema: ListingFieldSchema[] = [
  // Essential Section
  {
    name: "condition",
    label: "fields.condition",
    type: "select",
    options: ["new", "excellent", "good", "fair", "needsWork", "fixer-upper"],
    section: "essential",
    required: true,
  },
  {
    name: "floor",
    label: "fields.floor",
    type: "number",
    section: "essential",
    required: true,
  },
  {
    name: "totalFloors",
    label: "fields.totalFloors",
    type: "number",
    section: "essential",
    required: true,
  },
  {
    name: "parking",
    label: "fields.parking",
    type: "select",
    options: ["garage", "underground", "street", "none"],
    section: "essential",
    required: true,
  },
  {
    name: "elevator",
    label: "fields.elevator",
    type: "checkbox",
    section: "essential",
    required: true,
  },
  {
    name: "price",
    label: "fields.price",
    type: "number",
    section: "essential",
    required: true,
  },
  {
    name: "size",
    label: "fields.size",
    type: "number",
    section: "essential",
    required: true,
  },
  {
    name: "bedrooms",
    label: "fields.bedrooms",
    type: "number",
    section: "essential",
    required: true,
  },
  {
    name: "bathrooms",
    label: "fields.bathrooms",
    type: "number",
    section: "essential",
    required: true,
  },

  // Advanced Section
  {
    name: "balcony",
    label: "fields.balcony",
    type: "checkbox",
    section: "advanced",
    required: false,
  },
  {
    name: "storage",
    label: "fields.storage",
    type: "checkbox",
    section: "advanced",
    required: false,
  },
  {
    name: "heating",
    label: "fields.heating",
    type: "select",
    options: ["central", "individual", "district", "none"],
    section: "advanced",
    required: false,
  },
  {
    name: "cooling",
    label: "fields.cooling",
    type: "select",
    options: ["central", "split", "window", "none"],
    section: "advanced",
    required: false,
  },
  {
    name: "buildingAmenities",
    label: "fields.buildingAmenities",
    type: "multiselect",
    options: [
      "gym",
      "pool",
      "sauna",
      "playground",
      "security",
      "laundry",
      "storage",
      "roofDeck",
      "garden",
      "communityRoom",
      "businessCenter",
      "conferenceRoom",
      "concierge",
      "partyRoom",
      "petSpa",
      "bikeStorage",
      "coworkingSpace",
      "movieTheater",
      "guestSuite",
      "chargingStation",
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "energyRating",
    label: "fields.energyRating",
    type: "select",
    options: ["A+", "A", "B", "C", "D", "E", "F", "G", "unknown"],
    section: "advanced",
    required: false,
  },
  {
    name: "furnished",
    label: "fields.furnished",
    type: "select",
    options: ["yes", "no", "partially"],
    section: "advanced",
    required: false,
  },
  {
    name: "petPolicy",
    label: "fields.petPolicy",
    type: "select",
    options: ["allowed", "notAllowed", "negotiable"],
    section: "advanced",
    required: false,
  },
  {
    name: "view",
    label: "fields.view",
    type: "select",
    options: ["sea", "city", "garden", "mountain", "none"],
    section: "advanced",
    required: false,
  },
  {
    name: "securityFeatures",
    label: "fields.securityFeatures",
    type: "multiselect",
    options: [
      "alarm",
      "cctv",
      "concierge",
      "securityDoor",
      "fireAlarm",
      "intercom",
      "keycard",
      "securityGuard",
      "biometricAccess",
      "smartLocks",
      "videoDoorbells",
      "securedParking",
      "24hrSecurity",
      "gatedCommunity",
      "patrolService",
      "emergencyResponse",
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "fireSafety",
    label: "fields.fireSafety",
    type: "multiselect",
    options: [
      "sprinklers",
      "fireExtinguisher",
      "fireEscape",
      "fireAlarm",
      "smokeDetectors",
      "carbonMonoxideDetectors",
      "emergencyLighting",
      "fireResistantDoors",
      "fireBarriers",
      "evacuationPlan",
      "fireHoseReel",
      "emergencyExits",
      "fireControlPanel",
      "smokeEvacuation",
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "flooringType",
    label: "fields.flooringType",
    type: "select",
    options: [
      "tile",
      "hardwood",
      "engineeredWood",
      "laminate",
      "carpet",
      "vinyl",
      "marble",
      "granite",
      "concrete",
      "bamboo",
      "cork",
      "porcelain",
      "ceramic",
      "terrazzo",
      "slate",
      "other",
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "internetIncluded",
    label: "fields.internetIncluded",
    type: "checkbox",
    section: "advanced",
    required: false,
  },
  {
    name: "windowType",
    label: "fields.windowType",
    type: "select",
    options: [
      "doublePane",
      "triplePane",
      "standard",
      "soundproof",
      "lowE",
      "impactResistant",
      "tinted",
      "uv-protected",
      "argonFilled",
      "thermally-broken",
      "other",
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "accessibilityFeatures",
    label: "fields.accessibilityFeatures",
    type: "multiselect",
    options: [
      "wheelchair",
      "ramp",
      "wideHallways",
      "loweredCounters",
      "grabBars",
      "audioSystem",
      "braille",
      "stairLift",
      "elevatorAccess",
      "noSteps",
      "visualAlerts",
      "hearingLoop",
      "adjustableHeight",
      "tactilePaving",
      "automatedDoors",
      "accessibleParking",
      "rollinShower",
      "handrails",
      "emergencyPullCords",
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "kitchenFeatures",
    label: "fields.kitchenFeatures",
    type: "multiselect",
    options: [
      "island",
      "pantry",
      "customCabinetry",
      "stainlessAppliances",
      "gasStove",
      "inductionCooktop",
      "doubleOven",
      "wineStorage",
      "butlerPantry",
      "breakfastNook",
      "graniteCabinetry",
      "quartzCounters",
      "marbleCounters",
      "walkInPantry",
      "potFiller",
      "convectionOven",
      "instantHotWater",
      "waterFilter",
      "smartAppliances",
      "recyclingCenter",
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "bathroomFeatures",
    label: "fields.bathroomFeatures",
    type: "multiselect",
    options: [
      "dualVanities",
      "separateShower",
      "soakingTub",
      "jetTub",
      "steamShower",
      "bidet",
      "heatedFloors",
      "rainShower",
      "walkInShower",
      "ledMirror",
      "smartToilet",
      "naturalStone",
      "towelWarmer",
      "makeupVanity",
      "antifoggingMirrors",
      "motionSensors",
      "luxuryFixtures",
      "underSinkStorage",
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "renovationHistory",
    label: "fields.renovationHistory",
    type: "select",
    options: [
      "recentlyRenovated",
      "partiallyRenovated",
      "needsRenovation",
      "original",
      "historicallyPreserved",
      "completelyRemodeled",
      "cosmeticUpdates",
      "majorRenovation",
      "structuralRenovation",
      "inProgress",
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "nearbyAmenities",
    label: "fields.nearbyAmenities",
    type: "multiselect",
    options: [
      "publicTransport",
      "schools",
      "parks",
      "shopping",
      "restaurants",
      "medical",
      "entertainment",
      "groceryStores",
      "gym",
      "beach",
      "hiking",
      "biking",
      "culturalVenues",
      "worship",
      "daycare",
      "pharmacy",
      "bank",
      "library",
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "leaseTerms",
    label: "fields.leaseTerms",
    type: "multiselect",
    options: [
      "shortTerm",
      "longTerm",
      "flexible",
      "subletAllowed",
      "rentToOwn",
      "noDeposit",
      "firstMonthFree",
      "utilitiesIncluded",
      "petsAllowed",
      "smokingAllowed",
      "backgroundCheck",
      "incomeRequirement",
      "guarantorAccepted",
      "studentFriendly",
      "seniorLiving",
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "soundproofing",
    label: "fields.soundproofing",
    type: "select",
    options: ["premium", "enhanced", "standard", "basic", "none", "unknown"],
    section: "advanced",
    required: false,
  },
  {
    name: "viewType",
    label: "fields.viewType",
    type: "multiselect",
    options: [
      "cityView",
      "oceanView",
      "mountainView",
      "gardenView",
      "parkView",
      "lakeView",
      "poolView",
      "courtyardView",
      "streetView",
      "panoramic",
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "parkingType",
    label: "fields.parkingType",
    type: "select",
    options: [
      "covered",
      "uncovered",
      "garage",
      "carport",
      "street",
      "none",
      "valet",
      "assigned",
      "shared",
      "tandem",
      "mechanical",
      "underground",
      "electric",
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "utilities",
    label: "fields.utilities",
    type: "multiselect",
    options: [
      "water",
      "electricity",
      "gas",
      "trash",
      "internet",
      "cable",
      "heating",
      "sewer",
      "landline",
      "satellite",
      "fiberOptic",
      "solarPower",
      "recycling",
      "compost",
      "waterHeater",
      "waterSoftener",
      "pestControl",
      "landscaping",
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "smartHomeFeatures",
    label: "fields.smartHomeFeatures",
    type: "multiselect",
    options: [
      "smartThermostat",
      "smartLighting",
      "smartLocks",
      "voiceControl",
      "smartAppliances",
      "automatedBlinds",
      "securitySystem",
      "energyMonitoring",
      "smartSpeakers",
      "centralHub",
      "smartIrrigation",
      "smartGarage",
      "smartDoorbells",
      "smartWaterLeak",
      "smartAirQuality",
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "communityFeatures",
    label: "fields.communityFeatures",
    type: "multiselect",
    options: [
      "doorman",
      "elevator",
      "concierge",
      "sharedRooftop",
      "courtyard",
      "communityEvents",
      "petAmenities",
      "childcare",
      "shuttle",
      "groceryDelivery",
      "packageService",
      "dryCleaningService",
      "carWash",
      "bikeMaintenance",
      "coworkingSpace",
      "communityGarden",
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "exposureDirection",
    label: "fields.exposureDirection",
    type: "multiselect",
    options: ["north", "south", "east", "west"],
    section: "advanced",
    required: false,
  },
  {
    name: "storageType",
    label: "fields.storageType",
    type: "multiselect",
    options: ["basement", "attic", "closet", "external", "none"],
    section: "advanced",
    required: false,
  },
];
