import { ListingFieldSchema } from "@/types/listings";

export const apartmentSchema: ListingFieldSchema[] = [
  // Essential Section
  {
    name: "condition",
    label: "listings.condition",
    type: "select",
    options: ["new", "excellent", "good", "fair", "needsWork", "fixer-upper"],
    section: "essential",
    required: true,
  },
  {
    name: "floor",
    label: "listings.floor",
    type: "number",
    section: "essential",
    required: true,
  },
  {
    name: "totalFloors",
    label: "listings.totalFloors",
    type: "number",
    section: "essential",
    required: true,
  },
  {
    name: "parking",
    label: "listings.parking",
    type: "select",
    options: ["garage", "underground", "street", "none"],
    section: "essential",
    required: true,
  },
  {
    name: "elevator",
    label: "listings.elevator",
    type: "checkbox",
    section: "essential",
    required: true,
  },
  {
    name: "price",
    label: "listings.price",
    type: "number",
    section: "essential",
    required: true,
  },
  {
    name: "size",
    label: "listings.size",
    type: "number",
    section: "essential",
    required: true,
  },
  {
    name: "bedrooms",
    label: "listings.bedrooms",
    type: "number",
    section: "essential",
    required: true,
  },
  {
    name: "bathrooms",
    label: "listings.bathrooms",
    type: "number",
    section: "essential",
    required: true,
  },

  // Advanced Section
  {
    name: "balcony",
    label: "listings.balcony",
    type: "checkbox",
    section: "advanced",
    required: false,
  },
  {
    name: "storage",
    label: "listings.storage",
    type: "checkbox",
    section: "advanced",
    required: false,
  },
  {
    name: "heating",
    label: "listings.heating",
    type: "select",
    options: ["central", "individual", "district", "none"],
    section: "advanced",
    required: false,
  },
  {
    name: "cooling",
    label: "listings.cooling",
    type: "select",
    options: ["central", "split", "window", "none"],
    section: "advanced",
    required: false,
  },
  {
    name: "buildingAmenities",
    label: "listings.buildingAmenities",
    type: "multiselect",
    options: ["gym", "pool", "sauna", "playground", "security", "laundry", "storage", "roofDeck", "garden", "communityRoom", "businessCenter", "conferenceRoom", "concierge", "partyRoom", "petSpa", "bikeStorage", "coworkingSpace", "movieTheater", "guestSuite", "chargingStation"],
    section: "advanced",
    required: false,
  },
  {
    name: "energyRating",
    label: "listings.energyRating",
    type: "select",
    options: ["A+", "A", "B", "C", "D", "E", "F", "G", "unknown"],
    section: "advanced",
    required: false,
  },
  {
    name: "furnished",
    label: "listings.furnished",
    type: "select",
    options: ["yes", "no", "partially"],
    section: "advanced",
    required: false,
  },
  {
    name: "petPolicy",
    label: "listings.petPolicy",
    type: "select",
    options: ["allowed", "notAllowed", "negotiable"],
    section: "advanced",
    required: false,
  },
  {
    name: "view",
    label: "listings.view",
    type: "select",
    options: ["sea", "city", "garden", "mountain", "none"],
    section: "advanced",
    required: false,
  },
  {
    name: "securityFeatures",
    label: "listings.securityFeatures",
    type: "multiselect",
    options: ["alarm", "cctv", "concierge", "securityDoor", "fireAlarm", "intercom", "keycard", "securityGuard", "biometricAccess", "smartLocks", "videoDoorbells", "securedParking", "24hrSecurity", "gatedCommunity", "patrolService", "emergencyResponse"],
    section: "advanced",
    required: false,
  },
  {
    name: "fireSafety",
    label: "listings.fireSafety",
    type: "multiselect",
    options: ["sprinklers", "fireExtinguisher", "fireEscape", "fireAlarm", "smokeDetectors", "carbonMonoxideDetectors", "emergencyLighting", "fireResistantDoors", "fireBarriers", "evacuationPlan", "fireHoseReel", "emergencyExits", "fireControlPanel", "smokeEvacuation"],
    section: "advanced",
    required: false,
  },
  {
    name: "flooringType",
    label: "listings.flooringType",
    type: "select",
    options: ["tile", "hardwood", "engineeredWood", "laminate", "carpet", "vinyl", "marble", "granite", "concrete", "bamboo", "cork", "porcelain", "ceramic", "terrazzo", "slate", "other"],
    section: "advanced",
    required: false,
  },
  {
    name: "internetIncluded",
    label: "listings.internetIncluded",
    type: "checkbox",
    section: "advanced",
    required: false,
  },
  {
    name: "windowType",
    label: "listings.windowType",
    type: "select",
    options: ["doublePane", "triplePane", "standard", "soundproof", "lowE", "impactResistant", "tinted", "uv-protected", "argonFilled", "thermally-broken", "other"],
    section: "advanced",
    required: false,
  },
  {
    name: "accessibilityFeatures",
    label: "listings.accessibilityFeatures",
    type: "multiselect",
    options: [
      "wheelchair",
      "ramp",
      "wideHallways",
      "loweredCounters",
      "grabBars",
      "audioSystem",
      "braille",
      "stairLift",
      "elevatorAccess",
      "noSteps",
      "visualAlerts",
      "hearingLoop",
      "adjustableHeight",
      "tactilePaving",
      "automatedDoors",
      "accessibleParking",
      "rollinShower",
      "handrails",
      "emergencyPullCords"
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "kitchenFeatures",
    label: "listings.kitchenFeatures",
    type: "multiselect",
    options: [
      "island",
      "pantry",
      "customCabinetry",
      "stainlessAppliances",
      "gasStove",
      "inductionCooktop",
      "doubleOven",
      "wineStorage",
      "butlerPantry",
      "breakfastNook",
      "graniteCabinetry",
      "quartzCounters",
      "marbleCounters",
      "walkInPantry",
      "potFiller",
      "convectionOven",
      "instantHotWater",
      "waterFilter",
      "smartAppliances",
      "recyclingCenter"
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "bathroomFeatures",
    label: "listings.bathroomFeatures",
    type: "multiselect",
    options: [
      "dualVanities",
      "separateShower",
      "soakingTub",
      "jetTub",
      "steamShower",
      "bidet",
      "heatedFloors",
      "rainShower",
      "walkInShower",
      "ledMirror",
      "smartToilet",
      "naturalStone",
      "towelWarmer",
      "makeupVanity",
      "antifoggingMirrors",
      "motionSensors",
      "luxuryFixtures",
      "underSinkStorage"
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "renovationHistory",
    label: "listings.renovationHistory",
    type: "select",
    options: [
      "recentlyRenovated",
      "partiallyRenovated",
      "needsRenovation",
      "original",
      "historicallyPreserved",
      "completelyRemodeled",
      "cosmeticUpdates",
      "majorRenovation",
      "structuralRenovation",
      "inProgress"
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "nearbyAmenities",
    label: "listings.nearbyAmenities",
    type: "multiselect",
    options: [
      "publicTransport",
      "schools",
      "parks",
      "shopping",
      "restaurants",
      "medical",
      "entertainment",
      "groceryStores",
      "gym",
      "beach",
      "hiking",
      "biking",
      "culturalVenues",
      "worship",
      "daycare",
      "pharmacy",
      "bank",
      "library"
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "leaseTerms",
    label: "listings.leaseTerms",
    type: "multiselect",
    options: [
      "shortTerm",
      "longTerm",
      "flexible",
      "subletAllowed",
      "rentToOwn",
      "noDeposit",
      "firstMonthFree",
      "utilitiesIncluded",
      "petsAllowed",
      "smokingAllowed",
      "backgroundCheck",
      "incomeRequirement",
      "guarantorAccepted",
      "studentFriendly",
      "seniorLiving"
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "soundproofing",
    label: "listings.soundproofing",
    type: "select",
    options: [
      "premium",
      "enhanced",
      "standard",
      "basic",
      "none",
      "unknown"
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "viewType",
    label: "listings.viewType",
    type: "multiselect",
    options: [
      "cityView",
      "oceanView",
      "mountainView",
      "gardenView",
      "parkView",
      "lakeView",
      "poolView",
      "courtyardView",
      "streetView",
      "panoramic"
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "parkingType",
    label: "listings.parkingType",
    type: "select",
    options: ["covered", "uncovered", "garage", "carport", "street", "none", "valet", "assigned", "shared", "tandem", "mechanical", "underground", "electric"],
    section: "advanced",
    required: false,
  },
  {
    name: "utilities",
    label: "listings.utilities",
    type: "multiselect",
    options: [
      "water",
      "electricity",
      "gas",
      "trash",
      "internet",
      "cable",
      "heating",
      "sewer",
      "landline",
      "satellite",
      "fiberOptic",
      "solarPower",
      "recycling",
      "compost",
      "waterHeater",
      "waterSoftener",
      "pestControl",
      "landscaping"
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "smartHomeFeatures",
    label: "listings.smartHomeFeatures",
    type: "multiselect",
    options: [
      "smartThermostat",
      "smartLighting",
      "smartLocks",
      "voiceControl",
      "smartAppliances",
      "automatedBlinds",
      "securitySystem",
      "energyMonitoring",
      "smartSpeakers",
      "centralHub",
      "smartIrrigation",
      "smartGarage",
      "smartDoorbells",
      "smartWaterLeak",
      "smartAirQuality"
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "communityFeatures",
    label: "listings.communityFeatures",
    type: "multiselect",
    options: [
      "doorman",
      "elevator",
      "concierge",
      "sharedRooftop",
      "courtyard",
      "communityEvents",
      "petAmenities",
      "childcare",
      "shuttle",
      "groceryDelivery",
      "packageService",
      "dryCleaningService",
      "carWash",
      "bikeMaintenance",
      "coworkingSpace",
      "communityGarden"
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "exposureDirection",
    label: "listings.exposureDirection",
    type: "multiselect",
    options: ["north", "south", "east", "west"],
    section: "advanced",
    required: false,
  },
  {
    name: "storageType",
    label: "listings.storageType",
    type: "multiselect",
    options: ["basement", "attic", "closet", "external", "none"],
    section: "advanced",
    required: false,
  },
];
