import { ListingFieldSchema } from "@/types/listings";

export const houseSchema: ListingFieldSchema[] = [
  // Essential Section
  {
    name: "condition",
    label: "fields.condition",
    type: "select",
    options: ["new", "excellent", "good", "fair", "needsWork"],
    section: "essential",
    required: true,
  },
  {
    name: "livingArea",
    label: "fields.livingArea",
    type: "number",
    section: "essential",
    required: true,
  },
  {
    name: "halfBathrooms",
    label: "fields.halfBathrooms",
    type: "number",
    section: "essential",
    required: false,
  },
  {
    name: "stories",
    label: "fields.stories",
    type: "number",
    section: "essential",
    required: true,
  },
  {
    name: "parking",
    label: "fields.parking",
    type: "select",
    options: ["attachedGarage", "detachedGarage", "carport", "street", "none"],
    section: "essential",
    required: true,
  },
  {
    name: "parkingSpaces",
    label: "fields.parkingSpaces",
    type: "number",
    section: "essential",
    required: true,
  },
  {
    name: "constructionType",
    label: "fields.constructionType",
    type: "select",
    options: [
      "brick",
      "wood",
      "concrete",
      "steelFrame",
      "stonework",
      "stucco",
      "vinyl",
      "other",
    ],
    section: "essential",
    required: true,
  },

  // Advanced Section
  // HVAC & Energy
  {
    name: "heating",
    label: "fields.heating",
    type: "multiselect",
    options: [
      "central",
      "forcedAir",
      "radiant",
      "heatPump",
      "baseboard",
      "geothermal",
      "woodStove",
      "pelletStove",
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "cooling",
    label: "fields.cooling",
    type: "multiselect",
    options: [
      "central",
      "window",
      "split",
      "evaporative",
      "geothermal",
      "none",
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "energyFeatures",
    label: "fields.energyFeatures",
    type: "multiselect",
    options: [
      "solarPanels",
      "solarWaterHeater",
      "doubleGlazedWindows",
      "tripleGlazedWindows",
      "tanklessWaterHeater",
      "smartThermostat",
      "energyMonitoring",
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "energyRating",
    label: "fields.energyRating",
    type: "select",
    options: ["A+", "A", "B", "C", "D", "E", "F", "G", "unknown"],
    section: "advanced",
    required: false,
  },

  // Interior Features
  {
    name: "basement",
    label: "fields.basement",
    type: "select",
    options: ["finished", "unfinished", "partial", "walkout", "none"],
    section: "advanced",
    required: false,
  },
  {
    name: "basementFeatures",
    label: "fields.basementFeatures",
    type: "multiselect",
    options: [
      "bathroom",
      "kitchen",
      "bedroom",
      "separateEntrance",
      "wetBar",
      "workshop",
      "storage",
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "attic",
    label: "fields.attic",
    type: "select",
    options: ["finished", "unfinished", "none"],
    section: "advanced",
    required: false,
  },
  {
    name: "flooringTypes",
    label: "fields.flooringTypes",
    type: "multiselect",
    options: [
      "hardwood",
      "engineeredWood",
      "laminate",
      "tile",
      "carpet",
      "vinyl",
      "stone",
      "concrete",
      "bamboo",
      "cork",
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "windowFeatures",
    label: "fields.windowFeatures",
    type: "multiselect",
    options: [
      "bayWindow",
      "skylights",
      "gardenWindow",
      "doublePane",
      "triplePane",
      "lowE",
      "tinted",
      "soundproof",
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "kitchenFeatures",
    label: "fields.kitchenFeatures",
    type: "multiselect",
    options: [
      "island",
      "pantry",
      "graniteCabinetry",
      "stainlessAppliances",
      "gasStove",
      "doubleOven",
      "wineStorage",
      "butlerPantry",
      "breakfastNook",
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "bathroomFeatures",
    label: "fields.bathroomFeatures",
    type: "multiselect",
    options: [
      "dualVanities",
      "separateShower",
      "soakingTub",
      "jetTub",
      "steamShower",
      "bidet",
      "heated floors",
    ],
    section: "advanced",
    required: false,
  },

  // Exterior & Structure
  {
    name: "roofType",
    label: "fields.roofType",
    type: "select",
    options: [
      "asphaltShingle",
      "metalRoof",
      "tileClay",
      "slate",
      "flat",
      "greenRoof",
      "solar",
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "roofAge",
    label: "fields.roofAge",
    type: "number",
    section: "advanced",
    required: false,
  },
  {
    name: "foundation",
    label: "fields.foundation",
    type: "select",
    options: ["concrete", "crawlSpace", "slab", "pier", "stone", "other"],
    section: "advanced",
    required: false,
  },
  {
    name: "exteriorFeatures",
    label: "fields.exteriorFeatures",
    type: "multiselect",
    options: [
      "porch",
      "coveredPatio",
      "deck",
      "balcony",
      "fence",
      "securityGates",
      "outdoorKitchen",
      "firepit",
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "outdoorFeatures",
    label: "fields.outdoorFeatures",
    type: "multiselect",
    options: [
      "pool",
      "spa",
      "tennis",
      "garden",
      "sprinklers",
      "pond",
      "greenhouse",
      "rv parking",
      "workshop",
      "barn",
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "landscaping",
    label: "fields.landscaping",
    type: "multiselect",
    options: [
      "professional",
      "mature trees",
      "fruit trees",
      "garden beds",
      "lowMaintenance",
      "xeriscaping",
      "irrigation",
    ],
    section: "advanced",
    required: false,
  },

  // Systems & Utilities
  {
    name: "waterSystem",
    label: "fields.waterSystem",
    type: "select",
    options: ["municipal", "well", "shared well", "cistern"],
    section: "advanced",
    required: false,
  },
  {
    name: "sewerSystem",
    label: "fields.sewerSystem",
    type: "select",
    options: ["municipal", "septic", "other"],
    section: "advanced",
    required: false,
  },
  {
    name: "utilities",
    label: "fields.utilities",
    type: "multiselect",
    options: [
      "electricity",
      "naturalGas",
      "propane",
      "fiberInternet",
      "cable",
      "phone",
    ],
    section: "advanced",
    required: false,
  },

  // Smart Home & Security
  {
    name: "smartHomeFeatures",
    label: "fields.smartHomeFeatures",
    type: "multiselect",
    options: [
      "thermostat",
      "lighting",
      "security",
      "doorbell",
      "locks",
      "irrigation",
      "entertainment",
      "voiceControl",
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "securityFeatures",
    label: "fields.securityFeatures",
    type: "multiselect",
    options: [
      "alarm",
      "cameras",
      "gatedCommunity",
      "securityService",
      "smartLocks",
      "intercom",
      "safeRoom",
    ],
    section: "advanced",
    required: false,
  },

  // Community & HOA
  {
    name: "communityFeatures",
    label: "fields.communityFeatures",
    type: "multiselect",
    options: [
      "pool",
      "clubhouse",
      "gym",
      "tennis",
      "playground",
      "park",
      "lake",
      "trails",
      "golfCourse",
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "hoaFeatures",
    label: "fields.hoaFeatures",
    type: "multiselect",
    options: [
      "landscaping",
      "snow removal",
      "trash",
      "security",
      "commonAreas",
      "insurance",
    ],
    section: "advanced",
    required: false,
  },

  // Additional Features
  {
    name: "furnished",
    label: "fields.furnished",
    type: "select",
    options: ["fully", "partially", "unfurnished"],
    section: "advanced",
    required: false,
  },
  {
    name: "appliances",
    label: "fields.appliances",
    type: "multiselect",
    options: [
      "refrigerator",
      "dishwasher",
      "oven",
      "microwave",
      "washer",
      "dryer",
      "waterHeater",
      "waterSoftener",
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "petFeatures",
    label: "fields.petFeatures",
    type: "multiselect",
    options: ["dogRun", "petDoor", "fencedYard", "catDoor", "petWashStation"],
    section: "advanced",
    required: false,
  },
  {
    name: "accessibility",
    label: "fields.accessibility",
    type: "multiselect",
    options: [
      "wheelchair",
      "noSteps",
      "wideHallways",
      "elevator",
      "stairLift",
      "firstFloorBedroom",
      "modifiedBathroom",
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "storageFeatures",
    label: "fields.storageFeatures",
    type: "multiselect",
    options: [
      "attic",
      "basement",
      "shed",
      "garage",
      "workshop",
      "builtin",
      "mudRoom",
    ],
    section: "advanced",
    required: false,
  },
];
