import { ListingFieldSchema } from "@/types/listings";
import { Condition, FuelType, TransmissionType } from "@/types/enums";

export const commonVehicleFields: ListingFieldSchema[] = [
  // Essential Section
  {
    name: "color",
    label: "exteriorColor",
    type: "colorpicker",
    section: "essential",
    required: true,
  },
  {
    name: "interiorColor",
    label: "interiorColor",
    type: "colorpicker",
    section: "essential",
    required: true,
  },
  {
    name: "condition",
    label: "listings.condition",
    type: "select",
    options: Object.values(Condition),
    section: "essential",
    required: true,
  },
  {
    name: "previousOwners",
    label: "previousOwners",
    type: "number",
    section: "essential",
    required: false,
  },
  {
    name: "registrationStatus",
    label: "registrationStatus",
    type: "select",
    options: ["valid", "expired", "not_registered", "other"],
    section: "essential",
    required: false,
  },
  {
    name: "engine",
    label: "engine",
    type: "text",
    section: "essential",
    required: false,
  },
  {
    name: "fuelType",
    label: "fuelType",
    type: "select",
    options: Object.values(FuelType),
    section: "essential",
    required: false,
  },
  {
    name: "transmissionType",
    label: "listings.transmissionType",
    type: "select",
    options: Object.values(TransmissionType),
    section: "essential",
    required: false,
  },
  {
    name: "serviceHistory",
    label: "serviceHistory",
    type: "select",
    options: ["full", "partial", "no_history", "unknown"],
    section: "essential",
    required: false,
  },
  {
    name: "hours",
    label: "listings.hours",
    type: "number",
    section: "essential",
    required: false,
  },
  {
    name: "horsepower",
    label: "listings.horsepower",
    type: "number",
    section: "essential",
    required: false,
  },
  {
    name: "driveSystem",
    label: "listings.driveSystem",
    type: "select",
    options: ["2WD", "4WD", "MFWD", "AWD", "tracked"],
    section: "essential",
    required: false,
  },
  {
    name: "emissions",
    label: "listings.emissions",
    type: "select",
    options: ["Euro 6", "Euro 5", "Euro 4", "Euro 3", "Other", "Unknown"],
    section: "advanced",
    required: false,
  },
  {
    name: "warranty",
    label: "listings.warranty",
    type: "text",
    section: "advanced",
    required: false,
  },
];
