import { TransmissionType } from "@/types/enums";
import { ListingFieldSchema } from "@/types/listings";

export const tractorSchema: ListingFieldSchema[] = [
  // Essential Section

  {
    name: "color",
    label: "fields.exteriorColor",
    type: "colorpicker",
    section: "essential",
    required: true,
  },
  {
    name: "condition",
    label: "fields.condition",
    type: "select",
    options: [
      "new",
      "likeNew",
      "excellent",
      "good",
      "fair",
      "poor",
      "salvage",
      "forParts",
    ],
    section: "essential",
    required: true,
    validate: (value: string | number | boolean) =>
      !value ? "Condition is required" : null,
  },

  {
    name: "transmissionType",
    label: "fields.transmissionType",
    type: "select",
    options: Object.values(TransmissionType),
    section: "essential",
    required: true,
    validate: (value: string | number | boolean) =>
      !value ? "Transmission type is required" : null,
  },
  {
    name: "mileage",
    label: "fields.mileage",
    type: "number",
    section: "essential",
    required: true,
  },
  {
    name: "fuelType",
    label: "fields.fuelType",
    type: "select",
    options: [
      "",
      "diesel",
      "biodiesel",
      "gasoline",
      "electric",
      "hybrid",
      "lpg",
      "cng",
    ],
    section: "essential",
    required: true,
  },

  {
    name: "hours",
    label: "fields.hours",
    type: "number",
    section: "essential",
    required: true,
  },
  {
    name: "horsepower",
    label: "fields.horsepower",
    type: "number",
    section: "essential",
    required: true,
  },
  {
    name: "driveSystem",
    label: "fields.driveSystem",
    type: "select",
    options: ["2WD", "4WD", "MFWD", "AWD", "tracked"],
    section: "essential",
    required: true,
  },

  // Advanced Section
  // Engine & Performance
  {
    name: "engineSpecs",
    label: "fields.engineSpecs",
    type: "multiselect",
    options: [
      "turbocharged",
      "intercooled",
      "directInjection",
      "commonRail",
      "mechanicalInjection",
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "engineManufacturer",
    label: "fields.engineManufacturer",
    type: "text",
    section: "advanced",
    required: false,
  },
  {
    name: "engineModel",
    label: "fields.engineModel",
    type: "text",
    section: "advanced",
    required: false,
  },
  {
    name: "displacement",
    label: "fields.displacement",
    type: "text",
    section: "advanced",
    required: false,
  },
  {
    name: "cylinders",
    label: "fields.cylinders",
    type: "select",
    options: ["2", "3", "4", "5", "6", "8", "other"],
    section: "advanced",
    required: false,
  },
  {
    name: "torque",
    label: "fields.torque",
    type: "number",
    section: "advanced",
    required: false,
  },
  {
    name: "emissions",
    label: "fields.emissions",
    type: "select",
    options: [
      "Tier4Final",
      "Tier4Interim",
      "Tier3",
      "Tier2",
      "StageV",
      "StageIV",
      "StageIIIB",
      "other",
    ],
    section: "advanced",
    required: false,
  },

  // Hydraulics & PTO
  {
    name: "hydraulicSystem",
    label: "fields.hydraulicSystem",
    type: "select",
    options: ["open", "closed", "loadSensing", "pressureCompensated", "other"],
    section: "advanced",
    required: false,
  },
  {
    name: "hydraulicFlow",
    label: "fields.hydraulicFlow",
    type: "number",
    section: "advanced",
    required: false,
  },
  {
    name: "hydraulicOutlets",
    label: "fields.hydraulicOutlets",
    type: "multiselect",
    options: [
      "standard",
      "deluxe",
      "electrohydraulic",
      "powerBeyond",
      "frontRemotes",
      "midRemotes",
      "rearRemotes",
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "ptoSystem",
    label: "fields.ptoSystem",
    type: "multiselect",
    options: [
      "rear540",
      "rear1000",
      "rearDual",
      "mid",
      "front",
      "groundSpeed",
      "independent",
      "reversible",
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "ptoHorsepower",
    label: "fields.ptoHorsepower",
    type: "number",
    section: "advanced",
    required: false,
  },

  // Implements & Attachments
  {
    name: "frontAttachments",
    label: "fields.frontAttachments",
    type: "multiselect",
    options: [
      "loader",
      "dozer",
      "snowblower",
      "mower",
      "broom",
      "forks",
      "grapple",
      "bucket",
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "rearAttachments",
    label: "fields.rearAttachments",
    type: "multiselect",
    options: [
      "backhoe",
      "cultivator",
      "plow",
      "harrow",
      "sprayer",
      "baler",
      "mower",
      "rake",
    ],
    section: "advanced",
    required: false,
  },
  {
    name: "threePointHitch",
    label: "fields.threePointHitch",
    type: "select",
    options: ["category1", "category2", "category3", "category4", "none"],
    section: "advanced",
    required: false,
  },
  {
    name: "hitchCapacity",
    label: "fields.hitchCapacity",
    type: "number",
    section: "advanced",
    required: false,
  },
 // Maintenance & Documentation
 {
  name: "serviceHistory",
  label: "fields.serviceHistory",
  type: "multiselect",
  options: [
    "fullDealerHistory",
    "partialDealerHistory",
    "fullServiceRecords",
    "partialServiceRecords",
    "noHistory",
  ],
  section: "advanced",
  required: false,
},
{
  name: "warranty",
  label: "fields.warranty",
  type: "select",
  options: [
    "manufacturer",
    "extended",
    "powertrain",
    "comprehensive",
    "none",
  ],
  section: "advanced",
  required: false,
},
{
  name: "modifications",
  label: "fields.modifications",
  type: "text",
  section: "advanced",
  required: false,
},
{
  name: "electricalSystem",
  label: "fields.electricalSystem",
  type: "select",
  options: ["12V", "24V", "dual", "other"],
  section: "advanced",
  required: false,
},
  // ================= VEHICLE FEATURES =================
  {
    name: "features",
    label: "fields.vehicleFeatures",
    type: "featureGroup",
    section: "advanced",
    required: false,
    featureGroups: {
      cab: {
        label: "Cab Features",
        features: [
          {
            name: "airConditioning",
            label: "Air Conditioning",
            type: "toggle",
          },
          { name: "heating", label: "Heating", type: "toggle" },
          { name: "airSuspension", label: "Air Suspension", type: "toggle" },
          { name: "soundproofing", label: "Soundproofing", type: "toggle" },
          { name: "radio", label: "Radio", type: "toggle" },
          { name: "bluetooth", label: "Bluetooth", type: "toggle" },
          { name: "powerWindows", label: "Power Windows", type: "toggle" },
          { name: "sunroof", label: "Sunroof", type: "toggle" },
        ],
      },
      seating: {
        label: "Seating Features",
        features: [
          {
            name: "airSuspensionSeat",
            label: "Air Suspension Seat",
            type: "toggle",
          },
          { name: "mechanicalSeat", label: "Mechanical Seat", type: "toggle" },
          { name: "heatedSeat", label: "Heated Seat", type: "toggle" },
          { name: "ventilatedSeat", label: "Ventilated Seat", type: "toggle" },
          { name: "instructorSeat", label: "Instructor Seat", type: "toggle" },
          { name: "swivelSeat", label: "Swivel Seat", type: "toggle" },
        ],
      },
      steering: {
        label: "Steering Features",
        features: [
          { name: "powerSteering", label: "Power Steering", type: "toggle" },
          {
            name: "hydrostaticSteering",
            label: "Hydrostatic Steering",
            type: "toggle",
          },
          { name: "autoSteer", label: "Auto Steer", type: "toggle" },
          {
            name: "gpsReadySteering",
            label: "GPS Ready Steering",
            type: "toggle",
          },
          {
            name: "joystickSteering",
            label: "Joystick Steering",
            type: "toggle",
          },
        ],
      },
      lighting: {
        label: "Lighting Features",
        features: [
          { name: "halogenLights", label: "Halogen Lights", type: "toggle" },
          { name: "ledLights", label: "LED Lights", type: "toggle" },
          { name: "xenonLights", label: "Xenon Lights", type: "toggle" },
          { name: "workLights", label: "Work Lights", type: "toggle" },
          { name: "beaconLights", label: "Beacon Lights", type: "toggle" },
          { name: "roadLights", label: "Road Lights", type: "toggle" },
          { name: "cabLights", label: "Cab Lights", type: "toggle" },
        ],
      },
      technology: {
        label: "Technology Features",
        features: [
          { name: "gps", label: "GPS", type: "toggle" },
          {
            name: "autoSteerTech",
            label: "Auto Steer Technology",
            type: "toggle",
          },
          {
            name: "variableRateTech",
            label: "Variable Rate Technology",
            type: "toggle",
          },
          { name: "sectionControl", label: "Section Control", type: "toggle" },
          {
            name: "yieldMonitoring",
            label: "Yield Monitoring",
            type: "toggle",
          },
          { name: "telemetry", label: "Telemetry", type: "toggle" },
          { name: "digitalMonitor", label: "Digital Monitor", type: "toggle" },
          {
            name: "touchscreenMonitor",
            label: "Touchscreen Monitor",
            type: "toggle",
          },
          {
            name: "performanceMonitor",
            label: "Performance Monitor",
            type: "toggle",
          },
          {
            name: "implementMonitor",
            label: "Implement Monitor",
            type: "toggle",
          },
          { name: "cameraMonitor", label: "Camera Monitor", type: "toggle" },
        ],
      },
    },
  },


 
];
