export default {
  content: [
    './src/**/*.{js,jsx,ts,tsx}',
    './index.html',
    './src/components/**/*.{js,jsx,ts,tsx}',
    './src/pages/**/*.{js,jsx,ts,tsx}',
    '!./src/**/*.test.{js,jsx,ts,tsx}',
    '!./src/**/*.spec.{js,jsx,ts,tsx}',
  ],
  css: [
    './src/assets/css/index.css',
  ],
  defaultExtractor: content => content.match(/[A-Za-z0-9-_:/]+/g) || [],
  safelist: [
    // Critical layout classes only
    'hidden', 'block', 'flex', 'grid', 'container',
    'rtl', 'ltr', 'dark',
    'text-right', 'text-left', 'text-center',
    'w-full', 'h-full', 'min-h-screen',
    'p-4', 'm-4', 'px-4', 'py-4', 'mx-4', 'my-4',
    'text-sm', 'text-base', 'text-lg', 'text-xl',
    'bg-white', 'bg-gray-50', 'bg-gray-100',
    'border-gray-200', 'border-gray-300',
    'rounded', 'rounded-lg', 'rounded-xl',
    'shadow', 'shadow-lg',
  ],
  blocklist: [
    // Aggressively block unused Tailwind features
    /^ring-/,
    /^backdrop-/,
    /^translate-/,
    /^rotate-/,
    /^skew-/,
    /^scale-/,
    /^transform-/,
    /^blur-/,
    /^brightness-/,
    /^contrast-/,
    /^grayscale-/,
    /^hue-rotate-/,
    /^invert-/,
    /^invert/,
    /^saturate-/,
    /^sepia-/,
    // Target gradient utilities causing 17KB unused
    /^from-/,
    /^to-/,
    /^via-/,
    /^bg-gradient-/,
    /^gradient-/,
    /^bg-\w+-50/,
    /^bg-\w+-100/,
    /^bg-\w+-200/,
    /^bg-\w+-300/,
    /^bg-\w+-400/,
    /^bg-\w+-500/,
    /^bg-\w+-600/,
    /^bg-\w+-700/,
    /^bg-\w+-800/,
    /^bg-\w+-900/,
    /^bg-\w+-950/,
    /^text-\w+-50/,
    /^text-\w+-100/,
    /^text-\w+-200/,
    /^text-\w+-300/,
    /^text-\w+-400/,
    /^text-\w+-500/,
    /^text-\w+-600/,
    /^text-\w+-700/,
    /^text-\w+-800/,
    /^text-\w+-900/,
    /^text-\w+-950/,
    /^backdrop-blur-/,
    /^backdrop-brightness-/,
    /^backdrop-contrast-/,
    /^backdrop-grayscale/,
    /^backdrop-hue-rotate-/,
    /^backdrop-opacity-/,
    /^backdrop-saturate-/,
    /^backdrop-sepia-/,
    /^skew-/,
    /^scale-/,
    /^rotate-/,
    /^translate-/,
    /^origin-/,
    /^will-change-/,
    /^isolate/,
    /^mix-blend-/,
    /^bg-blend-/,
  ],
  keyframes: true,
  fontFace: true,
  variables: true,
};
